{{-- <div class="tailwind-scrollbar relative my-3.5 overflow-x-auto overflow-y-hidden border-b border-[var(--color-border)] pb-2.5 pt-1 transition-colors duration-300 [scrollbar-width:thin] [-webkit-overflow-scrolling:touch]"
    id="sportStripWrapper">
    <div class="flex min-w-max gap-x-3.5 whitespace-nowrap" id="sportSelector">
        <a href="{{ route('football.home') }}" class="sport-chip active-sport shrink-0 cursor-pointer rounded-[40px] border border-transparent bg-[var(--color-chip-bg)] px-3.5 py-[5px] text-sm font-medium text-[var(--color-text-secondary)] transition-colors duration-100 [&.active-sport]:border-[var(--color-primary)] [&.active-sport]:bg-[var(--color-primary)] [&.active-sport]:text-[var(--color-on-primary)] [&.active-sport]:shadow-[0_2px_8px_var(--color-primary-shadow)] [font-size:14px]  [padding:5px_14px] [border-radius:40px] [background:#f0f6fc] [color:#1e4763]  [transition:0.1s] [border:1px_solid_transparent]  dark:[background:#253a4a] dark:[color:#c8dae8] dark:[&.active-sport]:[background:#4a8ab5] dark:[&.active-sport]:[color:white] [&.active-sport]:[background:#0b2a40] [&.active-sport]:[color:white] [&.active-sport]:[border-color:#0b2a40] [&.active-sport]:[box-shadow:0_2px_8px_rgba(11,_42,_64,_0.12)]"
            data-sport="Soccer">Football</a>
        <a href="#"
            class="sport-chip shrink-0 cursor-pointer rounded-[40px] border border-transparent bg-[var(--color-chip-bg)] px-3.5 py-[5px] text-sm font-medium text-[var(--color-text-secondary)] transition-colors duration-100 [&.active-sport]:border-[var(--color-primary)] [&.active-sport]:bg-[var(--color-primary)] [&.active-sport]:text-[var(--color-on-primary)] [&.active-sport]:shadow-[0_2px_8px_var(--color-primary-shadow)] [font-size:14px]  [padding:5px_14px] [border-radius:40px] [background:#f0f6fc] [color:#1e4763]  [transition:0.1s] [border:1px_solid_transparent]  dark:[background:#253a4a] dark:[color:#c8dae8] dark:[&.active-sport]:[background:#4a8ab5] dark:[&.active-sport]:[color:white] [&.active-sport]:[background:#0b2a40] [&.active-sport]:[color:white] [&.active-sport]:[border-color:#0b2a40] [&.active-sport]:[box-shadow:0_2px_8px_rgba(11,_42,_64,_0.12)]"
            data-sport="Tennis">Tennis</a>
        <a href="#"
            class="sport-chip shrink-0 cursor-pointer rounded-[40px] border border-transparent bg-[var(--color-chip-bg)] px-3.5 py-[5px] text-sm font-medium text-[var(--color-text-secondary)] transition-colors duration-100 [&.active-sport]:border-[var(--color-primary)] [&.active-sport]:bg-[var(--color-primary)] [&.active-sport]:text-[var(--color-on-primary)] [&.active-sport]:shadow-[0_2px_8px_var(--color-primary-shadow)] [font-size:14px]  [padding:5px_14px] [border-radius:40px] [background:#f0f6fc] [color:#1e4763]  [transition:0.1s] [border:1px_solid_transparent]  dark:[background:#253a4a] dark:[color:#c8dae8] dark:[&.active-sport]:[background:#4a8ab5] dark:[&.active-sport]:[color:white] [&.active-sport]:[background:#0b2a40] [&.active-sport]:[color:white] [&.active-sport]:[border-color:#0b2a40] [&.active-sport]:[box-shadow:0_2px_8px_rgba(11,_42,_64,_0.12)]"
            data-sport="Horse Racing">Horse Racing</a>
        <a href="#"
            class="sport-chip shrink-0 cursor-pointer rounded-[40px] border border-transparent bg-[var(--color-chip-bg)] px-3.5 py-[5px] text-sm font-medium text-[var(--color-text-secondary)] transition-colors duration-100 [&.active-sport]:border-[var(--color-primary)] [&.active-sport]:bg-[var(--color-primary)] [&.active-sport]:text-[var(--color-on-primary)] [&.active-sport]:shadow-[0_2px_8px_var(--color-primary-shadow)] [font-size:14px]  [padding:5px_14px] [border-radius:40px] [background:#f0f6fc] [color:#1e4763]  [transition:0.1s] [border:1px_solid_transparent]  dark:[background:#253a4a] dark:[color:#c8dae8] dark:[&.active-sport]:[background:#4a8ab5] dark:[&.active-sport]:[color:white] [&.active-sport]:[background:#0b2a40] [&.active-sport]:[color:white] [&.active-sport]:[border-color:#0b2a40] [&.active-sport]:[box-shadow:0_2px_8px_rgba(11,_42,_64,_0.12)]"
            data-sport="Greyhounds">Greyhounds</a>
        <a href="#"
            class="sport-chip shrink-0 cursor-pointer rounded-[40px] border border-transparent bg-[var(--color-chip-bg)] px-3.5 py-[5px] text-sm font-medium text-[var(--color-text-secondary)] transition-colors duration-100 [&.active-sport]:border-[var(--color-primary)] [&.active-sport]:bg-[var(--color-primary)] [&.active-sport]:text-[var(--color-on-primary)] [&.active-sport]:shadow-[0_2px_8px_var(--color-primary-shadow)] [font-size:14px]  [padding:5px_14px] [border-radius:40px] [background:#f0f6fc] [color:#1e4763]  [transition:0.1s] [border:1px_solid_transparent]  dark:[background:#253a4a] dark:[color:#c8dae8] dark:[&.active-sport]:[background:#4a8ab5] dark:[&.active-sport]:[color:white] [&.active-sport]:[background:#0b2a40] [&.active-sport]:[color:white] [&.active-sport]:[border-color:#0b2a40] [&.active-sport]:[box-shadow:0_2px_8px_rgba(11,_42,_64,_0.12)]"
            data-sport="Basketball">Basketball</a>
        <a href="#"
            class="sport-chip shrink-0 cursor-pointer rounded-[40px] border border-transparent bg-[var(--color-chip-bg)] px-3.5 py-[5px] text-sm font-medium text-[var(--color-text-secondary)] transition-colors duration-100 [&.active-sport]:border-[var(--color-primary)] [&.active-sport]:bg-[var(--color-primary)] [&.active-sport]:text-[var(--color-on-primary)] [&.active-sport]:shadow-[0_2px_8px_var(--color-primary-shadow)] [font-size:14px]  [padding:5px_14px] [border-radius:40px] [background:#f0f6fc] [color:#1e4763]  [transition:0.1s] [border:1px_solid_transparent]  dark:[background:#253a4a] dark:[color:#c8dae8] dark:[&.active-sport]:[background:#4a8ab5] dark:[&.active-sport]:[color:white] [&.active-sport]:[background:#0b2a40] [&.active-sport]:[color:white] [&.active-sport]:[border-color:#0b2a40] [&.active-sport]:[box-shadow:0_2px_8px_rgba(11,_42,_64,_0.12)]"
            data-sport="Cricket">Cricket</a>
        <a href="#"
            class="sport-chip shrink-0 cursor-pointer rounded-[40px] border border-transparent bg-[var(--color-chip-bg)] px-3.5 py-[5px] text-sm font-medium text-[var(--color-text-secondary)] transition-colors duration-100 [&.active-sport]:border-[var(--color-primary)] [&.active-sport]:bg-[var(--color-primary)] [&.active-sport]:text-[var(--color-on-primary)] [&.active-sport]:shadow-[0_2px_8px_var(--color-primary-shadow)] [font-size:14px]  [padding:5px_14px] [border-radius:40px] [background:#f0f6fc] [color:#1e4763]  [transition:0.1s] [border:1px_solid_transparent]  dark:[background:#253a4a] dark:[color:#c8dae8] dark:[&.active-sport]:[background:#4a8ab5] dark:[&.active-sport]:[color:white] [&.active-sport]:[background:#0b2a40] [&.active-sport]:[color:white] [&.active-sport]:[border-color:#0b2a40] [&.active-sport]:[box-shadow:0_2px_8px_rgba(11,_42,_64,_0.12)]"
            data-sport="Ice Hockey">Ice Hockey</a>
        <a href="#"
            class="sport-chip shrink-0 cursor-pointer rounded-[40px] border border-transparent bg-[var(--color-chip-bg)] px-3.5 py-[5px] text-sm font-medium text-[var(--color-text-secondary)] transition-colors duration-100 [&.active-sport]:border-[var(--color-primary)] [&.active-sport]:bg-[var(--color-primary)] [&.active-sport]:text-[var(--color-on-primary)] [&.active-sport]:shadow-[0_2px_8px_var(--color-primary-shadow)] [font-size:14px]  [padding:5px_14px] [border-radius:40px] [background:#f0f6fc] [color:#1e4763]  [transition:0.1s] [border:1px_solid_transparent]  dark:[background:#253a4a] dark:[color:#c8dae8] dark:[&.active-sport]:[background:#4a8ab5] dark:[&.active-sport]:[color:white] [&.active-sport]:[background:#0b2a40] [&.active-sport]:[color:white] [&.active-sport]:[border-color:#0b2a40] [&.active-sport]:[box-shadow:0_2px_8px_rgba(11,_42,_64,_0.12)]"
            data-sport="American Football">American Football</a>
        <a href="#"
            class="sport-chip shrink-0 cursor-pointer rounded-[40px] border border-transparent bg-[var(--color-chip-bg)] px-3.5 py-[5px] text-sm font-medium text-[var(--color-text-secondary)] transition-colors duration-100 [&.active-sport]:border-[var(--color-primary)] [&.active-sport]:bg-[var(--color-primary)] [&.active-sport]:text-[var(--color-on-primary)] [&.active-sport]:shadow-[0_2px_8px_var(--color-primary-shadow)] [font-size:14px]  [padding:5px_14px] [border-radius:40px] [background:#f0f6fc] [color:#1e4763]  [transition:0.1s] [border:1px_solid_transparent]  dark:[background:#253a4a] dark:[color:#c8dae8] dark:[&.active-sport]:[background:#4a8ab5] dark:[&.active-sport]:[color:white] [&.active-sport]:[background:#0b2a40] [&.active-sport]:[color:white] [&.active-sport]:[border-color:#0b2a40] [&.active-sport]:[box-shadow:0_2px_8px_rgba(11,_42,_64,_0.12)]"
            data-sport="Baseball">Baseball</a>
    </div>
</div> --}}
<div class="sport-selector flex flex-wrap items-center gap-1.5 border-b py-3    [gap:6px] [padding:10px_0_14px] [border-bottom:1px_solid_#e6edf6] [margin-bottom:14px] [transition:border-color_0.3s] dark:[border-bottom-color:#2a3f50] max-[768px]:[gap:6px] max-[768px]:flex-nowrap max-[768px]:overflow-x-auto max-[768px]:pb-2 max-[768px]:[scrollbar-width:thin] max-[768px]:[&_.sport-pill]:shrink-0" id="sportSelector">
    <a href="{{ route('football.home') }}" class="sport-pill active inline-flex items-center [gap:5px] [padding:6px_12px] [border-radius:20px] [font-size:12px] font-semibold bg-transparent [border:1px_solid_#d4e0ec] [color:#5a7d99] cursor-pointer [transition:0.2s] select-none [font-family:inherit] dark:[border-color:#3a5568] dark:[color:#8aaccc] [&:hover]:[border-color:#1a6b9c] [&:hover]:[color:#1a6b9c] dark:[&:hover]:[border-color:#4a8ab5] dark:[&:hover]:[color:#6aafdf] [&.active]:[background:#e8f2fc] [&.active]:[border-color:#1a6b9c] [&.active]:[color:#1a6b9c] [&.active]:[font-weight:700] dark:[&.active]:[background:#1a2e44] dark:[&.active]:[border-color:#4a8ab5] dark:[&.active]:[color:#6aafdf] max-[768px]:[padding:6px_10px] max-[768px]:[font-size:11px] max-[480px]:[padding:5px_9px] max-[480px]:[font-size:10.5px]" data-sport="football">⚽ {{ __('Football') }}</a>
    <button class="sport-pill inline-flex items-center [gap:5px] [padding:6px_12px] [border-radius:20px] [font-size:12px] font-semibold bg-transparent [border:1px_solid_#d4e0ec] [color:#5a7d99] cursor-pointer [transition:0.2s] select-none [font-family:inherit] dark:[border-color:#3a5568] dark:[color:#8aaccc] [&:hover]:[border-color:#1a6b9c] [&:hover]:[color:#1a6b9c] dark:[&:hover]:[border-color:#4a8ab5] dark:[&:hover]:[color:#6aafdf] [&.active]:[background:#e8f2fc] [&.active]:[border-color:#1a6b9c] [&.active]:[color:#1a6b9c] [&.active]:[font-weight:700] dark:[&.active]:[background:#1a2e44] dark:[&.active]:[border-color:#4a8ab5] dark:[&.active]:[color:#6aafdf] max-[768px]:[padding:6px_10px] max-[768px]:[font-size:11px] max-[480px]:[padding:5px_9px] max-[480px]:[font-size:10.5px]" data-sport="tennis">🎾 {{ __('Tennis') }}</button>
    <button class="sport-pill inline-flex items-center [gap:5px] [padding:6px_12px] [border-radius:20px] [font-size:12px] font-semibold bg-transparent [border:1px_solid_#d4e0ec] [color:#5a7d99] cursor-pointer [transition:0.2s] select-none [font-family:inherit] dark:[border-color:#3a5568] dark:[color:#8aaccc] [&:hover]:[border-color:#1a6b9c] [&:hover]:[color:#1a6b9c] dark:[&:hover]:[border-color:#4a8ab5] dark:[&:hover]:[color:#6aafdf] [&.active]:[background:#e8f2fc] [&.active]:[border-color:#1a6b9c] [&.active]:[color:#1a6b9c] [&.active]:[font-weight:700] dark:[&.active]:[background:#1a2e44] dark:[&.active]:[border-color:#4a8ab5] dark:[&.active]:[color:#6aafdf] max-[768px]:[padding:6px_10px] max-[768px]:[font-size:11px] max-[480px]:[padding:5px_9px] max-[480px]:[font-size:10.5px]" data-sport="horseracing">🏇 {{ __('Horse Racing') }}</button>
    <button class="sport-pill inline-flex items-center [gap:5px] [padding:6px_12px] [border-radius:20px] [font-size:12px] font-semibold bg-transparent [border:1px_solid_#d4e0ec] [color:#5a7d99] cursor-pointer [transition:0.2s] select-none [font-family:inherit] dark:[border-color:#3a5568] dark:[color:#8aaccc] [&:hover]:[border-color:#1a6b9c] [&:hover]:[color:#1a6b9c] dark:[&:hover]:[border-color:#4a8ab5] dark:[&:hover]:[color:#6aafdf] [&.active]:[background:#e8f2fc] [&.active]:[border-color:#1a6b9c] [&.active]:[color:#1a6b9c] [&.active]:[font-weight:700] dark:[&.active]:[background:#1a2e44] dark:[&.active]:[border-color:#4a8ab5] dark:[&.active]:[color:#6aafdf] max-[768px]:[padding:6px_10px] max-[768px]:[font-size:11px] max-[480px]:[padding:5px_9px] max-[480px]:[font-size:10.5px]" data-sport="greyhounds">🐕 {{ __('Greyhounds')}}</button>
    <button class="sport-pill inline-flex items-center [gap:5px] [padding:6px_12px] [border-radius:20px] [font-size:12px] font-semibold bg-transparent [border:1px_solid_#d4e0ec] [color:#5a7d99] cursor-pointer [transition:0.2s] select-none [font-family:inherit] dark:[border-color:#3a5568] dark:[color:#8aaccc] [&:hover]:[border-color:#1a6b9c] [&:hover]:[color:#1a6b9c] dark:[&:hover]:[border-color:#4a8ab5] dark:[&:hover]:[color:#6aafdf] [&.active]:[background:#e8f2fc] [&.active]:[border-color:#1a6b9c] [&.active]:[color:#1a6b9c] [&.active]:[font-weight:700] dark:[&.active]:[background:#1a2e44] dark:[&.active]:[border-color:#4a8ab5] dark:[&.active]:[color:#6aafdf] max-[768px]:[padding:6px_10px] max-[768px]:[font-size:11px] max-[480px]:[padding:5px_9px] max-[480px]:[font-size:10.5px]" data-sport="basketball">🏀 {{ __('Basketball')}}</button>
    <button class="sport-pill inline-flex items-center [gap:5px] [padding:6px_12px] [border-radius:20px] [font-size:12px] font-semibold bg-transparent [border:1px_solid_#d4e0ec] [color:#5a7d99] cursor-pointer [transition:0.2s] select-none [font-family:inherit] dark:[border-color:#3a5568] dark:[color:#8aaccc] [&:hover]:[border-color:#1a6b9c] [&:hover]:[color:#1a6b9c] dark:[&:hover]:[border-color:#4a8ab5] dark:[&:hover]:[color:#6aafdf] [&.active]:[background:#e8f2fc] [&.active]:[border-color:#1a6b9c] [&.active]:[color:#1a6b9c] [&.active]:[font-weight:700] dark:[&.active]:[background:#1a2e44] dark:[&.active]:[border-color:#4a8ab5] dark:[&.active]:[color:#6aafdf] max-[768px]:[padding:6px_10px] max-[768px]:[font-size:11px] max-[480px]:[padding:5px_9px] max-[480px]:[font-size:10.5px]" data-sport="cricket">🏏 {{ __('Cricket')}}</button>
    <button class="sport-pill inline-flex items-center [gap:5px] [padding:6px_12px] [border-radius:20px] [font-size:12px] font-semibold bg-transparent [border:1px_solid_#d4e0ec] [color:#5a7d99] cursor-pointer [transition:0.2s] select-none [font-family:inherit] dark:[border-color:#3a5568] dark:[color:#8aaccc] [&:hover]:[border-color:#1a6b9c] [&:hover]:[color:#1a6b9c] dark:[&:hover]:[border-color:#4a8ab5] dark:[&:hover]:[color:#6aafdf] [&.active]:[background:#e8f2fc] [&.active]:[border-color:#1a6b9c] [&.active]:[color:#1a6b9c] [&.active]:[font-weight:700] dark:[&.active]:[background:#1a2e44] dark:[&.active]:[border-color:#4a8ab5] dark:[&.active]:[color:#6aafdf] max-[768px]:[padding:6px_10px] max-[768px]:[font-size:11px] max-[480px]:[padding:5px_9px] max-[480px]:[font-size:10.5px]" data-sport="icehockey">🏒 {{ __('Ice Hockey') }}</button>
    <button class="sport-pill inline-flex items-center [gap:5px] [padding:6px_12px] [border-radius:20px] [font-size:12px] font-semibold bg-transparent [border:1px_solid_#d4e0ec] [color:#5a7d99] cursor-pointer [transition:0.2s] select-none [font-family:inherit] dark:[border-color:#3a5568] dark:[color:#8aaccc] [&:hover]:[border-color:#1a6b9c] [&:hover]:[color:#1a6b9c] dark:[&:hover]:[border-color:#4a8ab5] dark:[&:hover]:[color:#6aafdf] [&.active]:[background:#e8f2fc] [&.active]:[border-color:#1a6b9c] [&.active]:[color:#1a6b9c] [&.active]:[font-weight:700] dark:[&.active]:[background:#1a2e44] dark:[&.active]:[border-color:#4a8ab5] dark:[&.active]:[color:#6aafdf] max-[768px]:[padding:6px_10px] max-[768px]:[font-size:11px] max-[480px]:[padding:5px_9px] max-[480px]:[font-size:10.5px]" data-sport="americanfootball">🏈 {{ __('American Football') }}</button>
    <button class="sport-pill inline-flex items-center [gap:5px] [padding:6px_12px] [border-radius:20px] [font-size:12px] font-semibold bg-transparent [border:1px_solid_#d4e0ec] [color:#5a7d99] cursor-pointer [transition:0.2s] select-none [font-family:inherit] dark:[border-color:#3a5568] dark:[color:#8aaccc] [&:hover]:[border-color:#1a6b9c] [&:hover]:[color:#1a6b9c] dark:[&:hover]:[border-color:#4a8ab5] dark:[&:hover]:[color:#6aafdf] [&.active]:[background:#e8f2fc] [&.active]:[border-color:#1a6b9c] [&.active]:[color:#1a6b9c] [&.active]:[font-weight:700] dark:[&.active]:[background:#1a2e44] dark:[&.active]:[border-color:#4a8ab5] dark:[&.active]:[color:#6aafdf] max-[768px]:[padding:6px_10px] max-[768px]:[font-size:11px] max-[480px]:[padding:5px_9px] max-[480px]:[font-size:10.5px]" data-sport="baseball">⚾ {{ __('Baseball')}}</button>
</div>
