<div class="filters-bar flex flex-col gap-2 py-3 dark:[border-bottom-color:#2a3f50] [padding:10px_0] [margin-bottom:12px] [transition:border-color_0.3s]" id="filtersBar">
    <div class="flex w-full flex-wrap items-center gap-2 max-[768px]:flex-nowrap max-[768px]:overflow-x-auto max-[768px]:pb-1 max-[768px]:[scrollbar-width:thin] max-[768px]:[&_.filter-pill]:shrink-0" data-filter-row="primary">
    <button class="filter-pill active inline-flex items-center [gap:6px] [padding:7px_14px] [border-radius:30px] [font-size:12.5px] font-semibold [background:#f0f6fc] [border:1px_solid_#d4e0ec] [color:#2a4d66] cursor-pointer [transition:0.2s] select-none [font-family:inherit] dark:[background:#1f3444] dark:[border-color:#3a5568] dark:[color:#b0c8dd] [&:hover]:[border-color:#1a6b9c] [&:hover]:[color:#1a6b9c] dark:[&:hover]:[border-color:#4a8ab5] dark:[&:hover]:[color:#6aafdf] [&.active]:[background:linear-gradient(135deg,_#0b2a40,_#1a6b9c)] [&.active]:[border-color:#1a6b9c] [&.active]:[color:white] dark:[&.active]:[background:linear-gradient(135deg,_#1a6b9c,_#4a8ab5)] dark:[&.active]:[border-color:#4a8ab5] max-[768px]:[padding:6px_10px] max-[768px]:[font-size:11px] max-[480px]:[padding:5px_9px] max-[480px]:[font-size:10.5px]" data-filter="all"><i class="fas fa-layer-group"></i> {{ __('All') }}</button>
    <button class="filter-pill inline-flex items-center [gap:6px] [padding:7px_14px] [border-radius:30px] [font-size:12.5px] font-semibold [background:#f0f6fc] [border:1px_solid_#d4e0ec] [color:#2a4d66] cursor-pointer [transition:0.2s] select-none [font-family:inherit] dark:[background:#1f3444] dark:[border-color:#3a5568] dark:[color:#b0c8dd] [&:hover]:[border-color:#1a6b9c] [&:hover]:[color:#1a6b9c] dark:[&:hover]:[border-color:#4a8ab5] dark:[&:hover]:[color:#6aafdf] [&.active]:[background:linear-gradient(135deg,_#0b2a40,_#1a6b9c)] [&.active]:[border-color:#1a6b9c] [&.active]:[color:white] dark:[&.active]:[background:linear-gradient(135deg,_#1a6b9c,_#4a8ab5)] dark:[&.active]:[border-color:#4a8ab5] max-[768px]:[padding:6px_10px] max-[768px]:[font-size:11px] max-[480px]:[padding:5px_9px] max-[480px]:[font-size:10.5px]" data-filter="live"><i class="fas fa-circle" style="color:#c74e4e;font-size:8px;"></i> {{ __('Live') }}</button>
    <button class="filter-pill inline-flex items-center [gap:6px] [padding:7px_14px] [border-radius:30px] [font-size:12.5px] font-semibold [background:#f0f6fc] [border:1px_solid_#d4e0ec] [color:#2a4d66] cursor-pointer [transition:0.2s] select-none [font-family:inherit] dark:[background:#1f3444] dark:[border-color:#3a5568] dark:[color:#b0c8dd] [&:hover]:[border-color:#1a6b9c] [&:hover]:[color:#1a6b9c] dark:[&:hover]:[border-color:#4a8ab5] dark:[&:hover]:[color:#6aafdf] [&.active]:[background:linear-gradient(135deg,_#0b2a40,_#1a6b9c)] [&.active]:[border-color:#1a6b9c] [&.active]:[color:white] dark:[&.active]:[background:linear-gradient(135deg,_#1a6b9c,_#4a8ab5)] dark:[&.active]:[border-color:#4a8ab5] max-[768px]:[padding:6px_10px] max-[768px]:[font-size:11px] max-[480px]:[padding:5px_9px] max-[480px]:[font-size:10.5px]" data-filter="upcoming"><i class="fas fa-clock"></i> {{ __('Upcoming') }}</button>
    @if (!request()->routeIs('football.market-activity'))
        <button class="filter-pill inline-flex items-center [gap:6px] [padding:7px_14px] [border-radius:30px] [font-size:12.5px] font-semibold [background:#f0f6fc] [border:1px_solid_#d4e0ec] [color:#2a4d66] cursor-pointer [transition:0.2s] select-none [font-family:inherit] dark:[background:#1f3444] dark:[border-color:#3a5568] dark:[color:#b0c8dd] [&:hover]:[border-color:#1a6b9c] [&:hover]:[color:#1a6b9c] dark:[&:hover]:[border-color:#4a8ab5] dark:[&:hover]:[color:#6aafdf] [&.active]:[background:linear-gradient(135deg,_#0b2a40,_#1a6b9c)] [&.active]:[border-color:#1a6b9c] [&.active]:[color:white] dark:[&.active]:[background:linear-gradient(135deg,_#1a6b9c,_#4a8ab5)] dark:[&.active]:[border-color:#4a8ab5] max-[768px]:[padding:6px_10px] max-[768px]:[font-size:11px] max-[480px]:[padding:5px_9px] max-[480px]:[font-size:10.5px]" data-filter="finished"><i class="fas fa-flag-checkered"></i> {{ __('Finished') }}</button>
    @endif
    <button class="filter-pill inline-flex items-center [gap:6px] [padding:7px_14px] [border-radius:30px] [font-size:12.5px] font-semibold [background:#f0f6fc] [border:1px_solid_#d4e0ec] [color:#2a4d66] cursor-pointer [transition:0.2s] select-none [font-family:inherit] dark:[background:#1f3444] dark:[border-color:#3a5568] dark:[color:#b0c8dd] [&:hover]:[border-color:#1a6b9c] [&:hover]:[color:#1a6b9c] dark:[&:hover]:[border-color:#4a8ab5] dark:[&:hover]:[color:#6aafdf] [&.active]:[background:linear-gradient(135deg,_#0b2a40,_#1a6b9c)] [&.active]:[border-color:#1a6b9c] [&.active]:[color:white] dark:[&.active]:[background:linear-gradient(135deg,_#1a6b9c,_#4a8ab5)] dark:[&.active]:[border-color:#4a8ab5] max-[768px]:[padding:6px_10px] max-[768px]:[font-size:11px] max-[480px]:[padding:5px_9px] max-[480px]:[font-size:10.5px]" data-filter="favorites"><i class="fas fa-star" style="color:#e6b422;"></i> {{ __('Favorites') }}</button>
    @if (!request()->routeIs('football.market-activity'))
        <button class="filter-pill inline-flex items-center [gap:6px] [padding:7px_14px] [border-radius:30px] [font-size:12.5px] font-semibold [background:#f0f6fc] [border:1px_solid_#d4e0ec] [color:#2a4d66] cursor-pointer [transition:0.2s] select-none [font-family:inherit] dark:[background:#1f3444] dark:[border-color:#3a5568] dark:[color:#b0c8dd] [&:hover]:[border-color:#1a6b9c] [&:hover]:[color:#1a6b9c] dark:[&:hover]:[border-color:#4a8ab5] dark:[&:hover]:[color:#6aafdf] [&.active]:[background:linear-gradient(135deg,_#0b2a40,_#1a6b9c)] [&.active]:[border-color:#1a6b9c] [&.active]:[color:white] dark:[&.active]:[background:linear-gradient(135deg,_#1a6b9c,_#4a8ab5)] dark:[&.active]:[border-color:#4a8ab5] max-[768px]:[padding:6px_10px] max-[768px]:[font-size:11px] max-[480px]:[padding:5px_9px] max-[480px]:[font-size:10.5px]" data-filter="by_time"><i class="fas fa-sort-amount-down"></i> {{ __('By Time') }}</button>
    @endif
    </div>

    <div class="flex w-full flex-wrap items-center gap-2 max-[768px]:flex-nowrap max-[768px]:overflow-x-auto max-[768px]:pb-1 max-[768px]:[scrollbar-width:thin] max-[768px]:[&_.filter-pill]:shrink-0" data-filter-row="signals">
    <button class="filter-pill inline-flex items-center [gap:6px] [padding:7px_14px] [border-radius:30px] [font-size:12.5px] font-semibold [background:#f0f6fc] [border:1px_solid_#d4e0ec] [color:#2a4d66] cursor-pointer [transition:0.2s] select-none [font-family:inherit] dark:[background:#1f3444] dark:[border-color:#3a5568] dark:[color:#b0c8dd] [&:hover]:[border-color:#1a6b9c] [&:hover]:[color:#1a6b9c] dark:[&:hover]:[border-color:#4a8ab5] dark:[&:hover]:[color:#6aafdf] [&.active]:[background:linear-gradient(135deg,_#0b2a40,_#1a6b9c)] [&.active]:[border-color:#1a6b9c] [&.active]:[color:white] dark:[&.active]:[background:linear-gradient(135deg,_#1a6b9c,_#4a8ab5)] dark:[&.active]:[border-color:#4a8ab5] max-[768px]:[padding:6px_10px] max-[768px]:[font-size:11px] max-[480px]:[padding:5px_9px] max-[480px]:[font-size:10.5px]" data-filter="ht00"><i class="fas fa-futbol"></i> {{ __('HT 0-0') }}</button>
    <button class="filter-pill inline-flex items-center [gap:6px] [padding:7px_14px] [border-radius:30px] [font-size:12.5px] font-semibold [background:#f0f6fc] [border:1px_solid_#d4e0ec] [color:#2a4d66] cursor-pointer [transition:0.2s] select-none [font-family:inherit] dark:[background:#1f3444] dark:[border-color:#3a5568] dark:[color:#b0c8dd] [&:hover]:[border-color:#1a6b9c] [&:hover]:[color:#1a6b9c] dark:[&:hover]:[border-color:#4a8ab5] dark:[&:hover]:[color:#6aafdf] [&.active]:[background:linear-gradient(135deg,_#0b2a40,_#1a6b9c)] [&.active]:[border-color:#1a6b9c] [&.active]:[color:white] dark:[&.active]:[background:linear-gradient(135deg,_#1a6b9c,_#4a8ab5)] dark:[&.active]:[border-color:#4a8ab5] max-[768px]:[padding:6px_10px] max-[768px]:[font-size:11px] max-[480px]:[padding:5px_9px] max-[480px]:[font-size:10.5px]" data-filter="00_70"><i class="fas fa-hourglass-half"></i> {{ __("0-0 @ 70'") }}</button>
    <button class="filter-pill inline-flex items-center [gap:6px] [padding:7px_14px] [border-radius:30px] [font-size:12.5px] font-semibold [background:#f0f6fc] [border:1px_solid_#d4e0ec] [color:#2a4d66] cursor-pointer [transition:0.2s] select-none [font-family:inherit] dark:[background:#1f3444] dark:[border-color:#3a5568] dark:[color:#b0c8dd] [&:hover]:[border-color:#1a6b9c] [&:hover]:[color:#1a6b9c] dark:[&:hover]:[border-color:#4a8ab5] dark:[&:hover]:[color:#6aafdf] [&.active]:[background:linear-gradient(135deg,_#0b2a40,_#1a6b9c)] [&.active]:[border-color:#1a6b9c] [&.active]:[color:white] dark:[&.active]:[background:linear-gradient(135deg,_#1a6b9c,_#4a8ab5)] dark:[&.active]:[border-color:#4a8ab5] max-[768px]:[padding:6px_10px] max-[768px]:[font-size:11px] max-[480px]:[padding:5px_9px] max-[480px]:[font-size:10.5px]" data-filter="fav_losing"><i class="fas fa-arrow-down" style="color:#c74e4e;"></i> {{ __('Fav Losing') }}</button>
    <button class="filter-pill inline-flex items-center [gap:6px] [padding:7px_14px] [border-radius:30px] [font-size:12.5px] font-semibold [background:#f0f6fc] [border:1px_solid_#d4e0ec] [color:#2a4d66] cursor-pointer [transition:0.2s] select-none [font-family:inherit] dark:[background:#1f3444] dark:[border-color:#3a5568] dark:[color:#b0c8dd] [&:hover]:[border-color:#1a6b9c] [&:hover]:[color:#1a6b9c] dark:[&:hover]:[border-color:#4a8ab5] dark:[&:hover]:[color:#6aafdf] [&.active]:[background:linear-gradient(135deg,_#0b2a40,_#1a6b9c)] [&.active]:[border-color:#1a6b9c] [&.active]:[color:white] dark:[&.active]:[background:linear-gradient(135deg,_#1a6b9c,_#4a8ab5)] dark:[&.active]:[border-color:#4a8ab5] max-[768px]:[padding:6px_10px] max-[768px]:[font-size:11px] max-[480px]:[padding:5px_9px] max-[480px]:[font-size:10.5px]" data-filter="prematch_drops"><i class="fas fa-arrow-trend-down"></i> {{ __('Prematch Drops') }}</button>
    <button class="filter-pill inline-flex items-center [gap:6px] [padding:7px_14px] [border-radius:30px] [font-size:12.5px] font-semibold [background:#f0f6fc] [border:1px_solid_#d4e0ec] [color:#2a4d66] cursor-pointer [transition:0.2s] select-none [font-family:inherit] dark:[background:#1f3444] dark:[border-color:#3a5568] dark:[color:#b0c8dd] [&:hover]:[border-color:#1a6b9c] [&:hover]:[color:#1a6b9c] dark:[&:hover]:[border-color:#4a8ab5] dark:[&:hover]:[color:#6aafdf] [&.active]:[background:linear-gradient(135deg,_#0b2a40,_#1a6b9c)] [&.active]:[border-color:#1a6b9c] [&.active]:[color:white] dark:[&.active]:[background:linear-gradient(135deg,_#1a6b9c,_#4a8ab5)] dark:[&.active]:[border-color:#4a8ab5] max-[768px]:[padding:6px_10px] max-[768px]:[font-size:11px] max-[480px]:[padding:5px_9px] max-[480px]:[font-size:10.5px]" data-filter="market_shock"><i class="fas fa-bolt" style="color:#e6b422;"></i> {{ __('Market Shock') }}</button>
    <button class="filter-pill inline-flex items-center [gap:6px] [padding:7px_14px] [border-radius:30px] [font-size:12.5px] font-semibold [background:#f0f6fc] [border:1px_solid_#d4e0ec] [color:#2a4d66] cursor-pointer [transition:0.2s] select-none [font-family:inherit] dark:[background:#1f3444] dark:[border-color:#3a5568] dark:[color:#b0c8dd] [&:hover]:[border-color:#1a6b9c] [&:hover]:[color:#1a6b9c] dark:[&:hover]:[border-color:#4a8ab5] dark:[&:hover]:[color:#6aafdf] [&.active]:[background:linear-gradient(135deg,_#0b2a40,_#1a6b9c)] [&.active]:[border-color:#1a6b9c] [&.active]:[color:white] dark:[&.active]:[background:linear-gradient(135deg,_#1a6b9c,_#4a8ab5)] dark:[&.active]:[border-color:#4a8ab5] max-[768px]:[padding:6px_10px] max-[768px]:[font-size:11px] max-[480px]:[padding:5px_9px] max-[480px]:[font-size:10.5px]" data-filter="fav_not_winning"><i class="fas fa-hand-paper" style="color:#1a6b9c;"></i> {{ __('Fav Not Winning') }}</button>
    </div>
</div>
